name: estoi_clock
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  installed_apps: ^1.3.1
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_background_service: ^5.0.1
  flutter_isolate: ^2.0.4
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.0
  process_run: ^0.13.1
  usage_stats: ^1.2.0
  fluttertoast: ^8.2.2
  flutter_windowmanager: ^0.2.0
  flutter_fgbg: ^0.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqlite3: ^2.1.0
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
   uses-material-design: true
   assets:
     - assets/stoiclock.db
